language: ruby
rvm:
  - 2.2
gemfile:
  - Gemfile
  - test/gemfiles/activerecord32.gemfile
  - test/gemfiles/activerecord40.gemfile
  - test/gemfiles/activerecord41.gemfile
script: bundle exec rake test
before_script:
  - psql -c 'create database strong_migrations_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
